version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 54321:5432
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=mmo
      - POSTGRES_DB=goals
